version: '3.3'
services:
  crawler:
    image: wasgeit/crawler
    volumes:
    - ./db:/wasgeit/db
  server:
    image: wasgeit/server
    user: 1000:1000
    hostname: backend
    networks:
    - wasgeit
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
  frontend:
    image: wasgeit/frontend
    command: "nginx -g 'daemon off;'"
    depends_on:
    - backend
    networks:
    - wasgeit
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/log/nginx/:/var/log/nginx

networks:
  wasgeit: