version: '3.3'
services:
  crawler:
    image: wasgeit/crawler
    volumes:
    - ./db:/wasgeit/db
  server:
    image: wasgeit/server
    hostname: backend
    networks:
      - wasgeit
    volumes:
    - ./db:/wasgeit/db
  frontend:
    image: wasgeit/frontend
    depends_on:
      - backend
    networks:
      - wasgeit
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  wasgeit: