version: '3.3'
services:
  crawler:
    image: wasgeit/crawler
    user: 1000:1000
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
  server:
    image: wasgeit/server
    user: 1000:1000
    networks:
    - wasgeit
    volumes:
    - type: bind
      source: ./dbª
      target: /wasgeit/db
  frontend:
    image: wasgeit/frontend
    command: "nginx -g 'daemon off;'"
    environment:
      - VIRTUAL_HOST=wasgeit.ch,www.wasgeit.ch
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    depends_on:
    - server
    networks:
    - wasgeit
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/log/nginx/:/var/log/nginx

networks:
  wasgeit:
