version: '3.3'
services:
  crawler:
    image: wasgeit/crawler
    user: 1000:1000
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
    command: '--chromium-url http://chromium:9222'
    networks:
    - wasgeit
  server:
    image: wasgeit/server
    user: 1000:1000
    networks:
    - wasgeit
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
  frontend:
    image: wasgeit-frontend:react
    command: "nginx -g 'daemon off;'"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=wasgeit.ch,www.wasgeit.ch
      - CERT_NAME=cert
    depends_on:
    - server
    networks:
    - wasgeit
    volumes:
    - /var/log/nginx/:/var/log/nginx

networks:
  wasgeit:
