version: '3.3'
services:
  crawler:
    image: wasgeit/crawler:prod
    user: 1000:1000
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
    networks:
    - wasgeit
  server:
    image: wasgeit/server:prod
    user: 1000:1000
    networks:
    - wasgeit
    volumes:
    - type: bind
      source: ./db
      target: /wasgeit/db
  frontend:
    image: wasgeit/frontend:prod
    command: "nginx -g 'daemon off;'"
    expose:
      - "80"
    depends_on:
    - server
    networks:
    - wasgeit
    volumes:
    - /var/log/nginx/:/var/log/nginx

networks:
  wasgeit:
