version: '3.3'

services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - demo_wasgeit
      - prod_wasgeit
      - zuweiser_zuweiser
  headless-chromium:
    image: chromedp/headless-shell:77.0.3841.0
    user: nobody
    security_opt: 
      # courtesy of https://github.com/jessfraz/dotfiles/blob/master/etc/docker/seccomp/chrome.json
      - seccomp=chrome-seccomp-profile.json
    networks: 
      demo_wasgeit:
        aliases: 
          - chromium
      prod_wasgeit:
        aliases:
          - chromium
    entrypoint: /headless-shell/headless-shell
    command:
     - --remote-debugging-address=0.0.0.0 
     - --remote-debugging-port=9222 
     - --disable-gpu 
     - --headless
networks:
  demo_wasgeit:
    external: yes
  prod_wasgeit:
    external: yes
  zuweiser_zuweiser:
    external: yes
