version: '3.3'

services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - demo_wasgeit
      - prod_wasgeit
  headless-chromium:
    image: chromedp/headless-shell:latest
    networks: 
      demo_wasgeit:
        aliases: 
          - chromium
      prod_wasgeit:
        aliases:
          - chromium
    command: --disable-gpu
networks:
  demo_wasgeit:
    external: yes
  prod_wasgeit:
    external: yes